### ISSUE TITLE
Cannot install with yarn and node 14

### ISSUE THREAD

**Issue by riderx** [NativeScript/capacitor#11]
```
error /Users/***/Documents/Projects.nosync/Mimesis/node_modules/@nativescript/capacitor: Command failed.
Exit code: 1
Command: node dist/esm/postinstall --action install
Arguments: 
Directory: /Users/***/Documents/Projects.nosync/Mimesis/node_modules/@nativescript/capacitor
Output:
⚙️   @nativescript/capacitor installing...
undefined:14
    ],
    ^

SyntaxError: Unexpected token ] in JSON at position 293
    at JSON.parse (<anonymous>)
    at addProjectManagedNativeScript (/Users/***/Documents/Projects.nosync/Mimesis/node_modules/@nativescript/capacitor/dist/esm/postinstall.js:128:39)
    at Object.<anonymous> (/Users/***/Documents/Projects.nosync/Mimesis/node_modules/@nativescript/capacitor/dist/esm/postinstall.js:749:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

**Comment by NathanWalker** [comment]
Resolved with v2+
