### ISSUE TITLE
install fails when tsconfig.json contains a trailing comma

### ISSUE THREAD

**Issue by akvadrako** [NativeScript/capacitor#16]
For whatever reason, `tsconfig.json` is allowed to contain comments and trailing commas. The upstream default even has them. When I do `npm install @nativescript/capacitor` it works with comments, but fails with a poor error message if there is a trailing comma.

```
npm ERR! path /.../node_modules/@nativescript/capacitor
npm ERR! command failed
npm ERR! command sh -c node dist/esm/postinstall --action install
npm ERR! ⚙️   @nativescript/capacitor installing...
npm ERR! undefined:44
npm ERR! }
npm ERR! ^
npm ERR!
npm ERR! SyntaxError: Unexpected token } in JSON at position 1186
npm ERR!     at JSON.parse (<anonymous>)
npm ERR!     at addProjectManagedNativeScript (/home/dev/repo/apps/android/svelte-capacitor-git/node_modules/@nativescript/capacitor/dist/esm/postinstall.js:137:39)
npm ERR!     at Object.<anonymous> (/home/dev/repo/apps/android/svelte-capacitor-git/node_modules/@nativescript/capacitor/dist/esm/postinstall.js:565:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47
npm ERR!
npm ERR! Node.js v17.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2022-04-29T12_17_23_659Z-debug.log
```

- @nativescript/capacitor 2.0.2

**Comment by akvadrako** [comment]
Nevermind I see this is a duplicate of #2.
